"""
Seed Data Generator for DecisionGuard AI
Generates realistic, explicitly labelled synthetic inventory profiles across multiple industries
for high-scale stress-testing and demonstration of self-challenge risk calibration.
"""

SYNTHETIC_SEED_CATALOG = [
    {
        "sku": "SKU-MED-7023",
        "product_name": "Ultra-Cold mRNA Vaccine Vials (10-Dose Pack)",
        "category": "Pharmaceutical Cold Chain",
        "current_stock": 14,
        "safety_stock": 25,
        "reorder_point": 40,
        "target_stock_level": 100,
        "daily_velocity": 4.2,
        "supplier_lead_time_days": 6,
        "unit_cost_usd": 145.0,
        "selling_price_usd": 280.0,
        "supplier_moq": 20,
        "supplier_name": "BioPharma ColdLogistics",
        "supplier_reliability_score": 0.97,
        "upcoming_event": "Flu season vaccination drive in 14 days",
        "shelf_life_days": 21,
        "recent_demand_history_7d": [4, 5, 4, 3, 5, 6, 4],
        "notes": "[Synthetic Benchmark] Strict 21-day temperature-monitored shelf life. High spoilage cost."
    },
    {
        "sku": "SKU-AUTO-6019",
        "product_name": "Vented Ceramic Composite Brake Rotors (Pair)",
        "category": "Automotive Tier-1",
        "current_stock": 12,
        "safety_stock": 20,
        "reorder_point": 35,
        "target_stock_level": 90,
        "daily_velocity": 2.8,
        "supplier_lead_time_days": 18,
        "unit_cost_usd": 68.0,
        "selling_price_usd": 175.0,
        "supplier_moq": 30,
        "supplier_name": "Precision Braking Systems",
        "supplier_reliability_score": 0.89,
        "upcoming_event": "None",
        "warehouse_volume_cuft": 4.2,
        "recent_demand_history_7d": [3, 2, 3, 4, 2, 3, 3],
        "notes": "[Synthetic Benchmark] Heavy freight item with 18-day maritime transit lead time."
    },
    {
        "sku": "SKU-TECH-8045",
        "product_name": "Active Noise-Cancelling Spatial Audio Headphones",
        "category": "Consumer Electronics",
        "current_stock": 85,
        "safety_stock": 40,
        "reorder_point": 75,
        "target_stock_level": 220,
        "daily_velocity": 12.0,
        "supplier_lead_time_days": 8,
        "unit_cost_usd": 75.0,
        "selling_price_usd": 199.0,
        "supplier_moq": 50,
        "supplier_name": "AeroAcoustics Global",
        "supplier_reliability_score": 0.95,
        "upcoming_event": "Black Friday Cyber Week surge expected",
        "recent_demand_history_7d": [10, 12, 14, 15, 13, 11, 14],
        "notes": "[Synthetic Benchmark] High margin fast mover with strong seasonal demand elasticity."
    },
    {
        "sku": "SKU-BEAUTY-9011",
        "product_name": "Hyaluronic Acid Multi-Molecular Hydration Serum",
        "category": "Dermatological Cosmetics",
        "current_stock": 22,
        "safety_stock": 30,
        "reorder_point": 48,
        "target_stock_level": 140,
        "daily_velocity": 6.5,
        "supplier_lead_time_days": 10,
        "unit_cost_usd": 16.5,
        "selling_price_usd": 48.0,
        "supplier_moq": 40,
        "supplier_name": "DermaPure Labs",
        "supplier_reliability_score": 0.91,
        "upcoming_event": "Beauty Expo influencer feature",
        "shelf_life_days": 60,
        "recent_demand_history_7d": [6, 7, 5, 8, 7, 6, 7],
        "notes": "[Synthetic Benchmark] Moderate 60-day shelf life with high social marketing velocity variance."
    },
    {
        "sku": "SKU-IND-9055",
        "product_name": "Solid Carbide 4-Flute CNC End Mill Set",
        "category": "Industrial MRO & Tooling",
        "current_stock": 6,
        "safety_stock": 15,
        "reorder_point": 22,
        "target_stock_level": 60,
        "daily_velocity": 1.2,
        "supplier_lead_time_days": 15,
        "unit_cost_usd": 42.0,
        "selling_price_usd": 95.0,
        "supplier_moq": 20,
        "supplier_name": "Apex Tooling Solutions",
        "supplier_reliability_score": 0.72,
        "upcoming_event": "None",
        "recent_demand_history_7d": [1, 1, 2, 0, 1, 2, 1],
        "notes": "[Synthetic Benchmark] Critical machine-shop tool; vendor has low 72% fulfillment reliability."
    },
    {
        "sku": "SKU-FOOD-1044",
        "product_name": "Single-Origin Ethiopian Yirgacheffe Beans (1kg)",
        "category": "Specialty Food & Beverage",
        "current_stock": 16,
        "safety_stock": 24,
        "reorder_point": 36,
        "target_stock_level": 110,
        "daily_velocity": 4.8,
        "supplier_lead_time_days": 7,
        "unit_cost_usd": 11.0,
        "selling_price_usd": 26.0,
        "supplier_moq": 25,
        "supplier_name": "Equator Roast Direct",
        "supplier_reliability_score": 0.93,
        "upcoming_event": "Winter cafe seasonal menu launch",
        "shelf_life_days": 40,
        "recent_demand_history_7d": [5, 4, 5, 6, 4, 5, 5],
        "notes": "[Synthetic Benchmark] Fresh-roasted coffee beans; degrades after 40 days."
    },
    {
        "sku": "SKU-HOME-2089",
        "product_name": "Ultrasonic Cool Mist Smart Air Humidifier (4L)",
        "category": "Smart Home Appliances",
        "current_stock": 35,
        "safety_stock": 25,
        "reorder_point": 50,
        "target_stock_level": 160,
        "daily_velocity": 5.0,
        "supplier_lead_time_days": 12,
        "unit_cost_usd": 26.0,
        "selling_price_usd": 69.99,
        "supplier_moq": 30,
        "supplier_name": "Nordic Climate Devices",
        "supplier_reliability_score": 0.90,
        "upcoming_event": "Dry winter climate transition",
        "warehouse_volume_cuft": 1.8,
        "recent_demand_history_7d": [4, 5, 6, 5, 6, 4, 5],
        "notes": "[Synthetic Benchmark] Bulky boxed appliance with steady seasonal demand."
    }
]
